### ISSUE TITLE
A cleaner way to embed the script

### ISSUE THREAD

**Issue by aaronharding** [MaxArt2501/object-observe#6] opened 2015-05-21 19:42 UTC
Hey,

The polyfill is great, although I would suggest this as a way to embed it on the site:

``` html
<script>Object.observe || document.write('<script src="path/to/object-observe.js"><\/script>')</script>
```

Saves a http request and how ever many kbs, but it's just a bit cleaner imo.

**Comment by MaxArt2501** [comment] 2015-05-21 21:34
I wouldn't say it's "cleaner" (adding Javascript directly in the page, plus `document.write`), but it surely is effective. I'll consider adding it to the documentation, but there are some points to be considered.

Generally speaking, there are many ways to conditionally loading the polyfill. With an AMD loader, it's as easy as adding the script to the dependency list. And I've mentioned a similar way in the [extended documentation](/MaxArt2501/object-observe/blob/master/doc/index.md#nodejs) in CommonJS environments.

The problem is that all these conditional loads behave quite bad when it comes to _compiling_ the project, which is the preferred way to serve an application these days - until HTTP 2.0 will become widespread enough. You could use browserify, webpack, R.js... they are all going to fail if you're building on the server side using  a client side test.

So, the alternatives are:
- using a trick like your one, and leaving the polyfill outside the compiled script;
- include the polyfill anyway, which is currenyl only 1768 bytes large for the minified and gzipped "lite" version (or 2269 for the regular one).

In order to save a request (which would be performed by every browser except Chrome and Opera as of today), I'd personally go for the second solution. That's why I suggested to test-load the polyfill in node.js only, since you wouldn't have to build a big script file for your application.

Either way, it's probably worth adding some considerations about loading the polyfill in the aforementioned documentation. Thank you for the suggestion!

**Comment by aaronharding** [comment] 2015-05-22 11:48
Oh, I guess I was assuming from a non node point of view here. I didn't see any vanilla environment examples, and only saw the `observe` check in the first line of the poly. I also am not familiar with the tools that you listed, I usually build my apps with npm scripts and gulp.. perhaps if I was I would understand more of the concern here.

Do you mind elaborating why the tools you mentioned would fail to compile with this example?

The reason I used document.write is that it's a render blocking execution, so declaring this before scripts where `observe` is being called will ensure you've set the poly in place. If you are waiting for the documentary to be ready before initialising the script, then of course, load the poly asynchronously!

Thanks for the super detailed reply tho!

**Comment by MaxArt2501** [comment] 2015-05-22 13:26
The tools I mentioned combine all the referenced libraries together in one big script file, that (presumably) should be loaded once per session by the client. For example, if you use [RequireJS](http://requirejs.org/), you could define your modules like this:

``` js
var dependencies = [ "jquery" ];
if (!Object.observe) dependencies.push("object-observe-lite.min");
define(dependencies, function($) {
    // Your code using $ and Object.observe here...
});
```

Now this works flawlessly on the client side, but if you want to use R.js (which is RequireJS' module packer) to create a single script file, so the client doesn't have to load every dependency independently, then you're going to have a problem because R.js not only does _not_ understand a more complex syntax for the dependencies like that on, but even if it did it can _not_ work properly because checking `Object.observe`'s support must be done on the _client_ every time a browser visits the page, not on the _server_ once and for all.

Similarly, if your packer is [browserify](http://browserify.org/) or [webpack](http://webpack.github.io/) or whatever you use to get CommonJS module syntax, you'll end up defining dependencies like this:

``` js
var $ = require("jquery");
if (!Object.observe) require("object.observe");
```

This may look nice, but when you compile the packer may either _always_ or _never_ include the polyfill - or maybe throw an exception... I don't know, I've never actually tried because the underlying problem still persists: if you want the polyfill to be loaded on a per case basis, you can't use a script that you've built on the server.

Just always include the polyfill in your dependencies and you're gold. _Or_ leave the polyfill out of your project's dependencies and load it on the client after performing a check:

``` html
<script>Object.observe || document.write('<script src="object-observe.js"></script>')</script>
<script src="application.js"></script>
```

But this would also mean that the client, if it doesn't support `O.o`, must _first_ load the polyfill, halting the application's script execution until it's loaded. As I said, I prefer the other solution.

Of course, if you do _not_ use a script packer of any sort, and load every script independently each with its `<script>` tag, your trick works like a charm. But this development pattern should be used for small projects only, nowadays.

I hope this is clear, but in any case ask away!

**Comment by MaxArt2501** [comment] 2015-08-02 10:30
Closing with updated documentation.

**Closed as completed by MaxArt2501** 2015-08-02 10:30 UTC
